import { EncyclopediaEntry } from '../../types';

export const HOW_THINGS_WORK_ENTRIES: EncyclopediaEntry[] = [
  {
    id: 'how-airplanes-fly',
    title: 'How Airplanes Fly (Aerodynamics)',
    symbol: '✈️',
    pronunciation: '(AIR-playnz and EHR-oh-die-NAM-iks)',
    category: 'how-things-work',
    tagline: 'How a 500-ton metal jet lifts gracefully into the blue sky using invisible air pressure.',
    analogy: {
      title: 'Water-Skiing on an Ocean of Air',
      story: 'You can’t see air, but it is made of trillions of tiny molecules! An airplane wing is curved on top and flat on the bottom (an airfoil shape). As the plane zooms forward, air has to race faster over the curved top, creating low pressure that sucks the plane up into the sky, just like water lifts a surfboard!',
      emoji: '🪁'
    },
    howItWorks: {
      title: 'The 4 Forces of Flight',
      points: [
        'Lift (Upward): Created by air rushing over specially curved wings (Bernoulli’s principle).',
        'Weight/Gravity (Downward): The downward pull of Earth’s gravity that wings must overcome.',
        'Thrust (Forward): The powerful push created by jet engines sucking air and blasting it back.',
        'Drag (Backward): The wind resistance trying to slow the aircraft down.'
      ]
    },
    anatomyDiagram: {
      headline: 'Parts of an Airplane',
      parts: [
        { label: 'Airfoil Wings', desc: 'Generate upward aerodynamic lift.' },
        { label: 'Jet Engines', desc: 'Create forward thrust by burning fuel with compressed air.' },
        { label: 'Rudder (Tail)', desc: 'Turns the nose left or right (yaw).' },
        { label: 'Elevators (Tail)', desc: 'Point the nose up to climb or down to descend (pitch).' }
      ]
    },
    funFacts: [
      'A Boeing 747 airplane has about 6 million individual parts assembled together!',
      'Commercial jets fly around 35,000 feet high where the air is thinner, using less fuel to glide faster.',
      'The Wright Brothers made the first powered airplane flight in 1903 — and it lasted only 12 seconds!'
    ],
    kidWords: [
      { word: 'Lift', emoji: '🛫', meaning: 'The upward aerodynamic force that opposes gravity and keeps planes in the sky.' },
      { word: 'Thrust', emoji: '🚀', meaning: 'The forward push generated by engines.' },
      { word: 'Airfoil', emoji: '🪶', meaning: 'The curved cross-section shape of a wing designed to create lift.' }
    ],
    didYouKnowOrigin: 'Birds provided the original blueprint for flight! Engineers studied how eagles curve their feathers to glide on thermal air currents without flapping.',
    microQuiz: {
      question: 'Which of the 4 flight forces lifts the airplane up into the clouds?',
      options: ['Lift', 'Gravity', 'Drag'],
      correctIndex: 0,
      explanation: 'Lift is created by the curved shape of wings moving through air, overcoming gravity!'
    },
    handsOnExperiment: {
      title: 'The Paper Strip Bernoulli Lift Trick',
      materials: ['A strip of paper about 2 inches wide and 8 inches long'],
      steps: [
        'Hold the short edge of the paper strip just under your bottom lip with both hands.',
        'Notice how the long end of the paper droops down towards the floor.',
        'Blow a steady, fast stream of air over the TOP curve of the paper.',
        'Watch in amazement as the droopy paper instantly rises straight up like magic!'
      ],
      explanation: 'Fast-moving air over the top creates lower pressure, and higher air pressure underneath pushes the paper up — the exact same way airplane wings work!',
      emoji: '📄'
    },
    kidTongueTwisterOrRhyme: 'Fast flying planes glide freely floating through fluffy foggy clouds!',
    seeAlso: [
      { id: 'air-element', title: 'Air & Atmosphere', category: 'earth-elements' },
      { id: 'letter-a', title: 'Letter A', category: 'alphabets' }
    ]
  },
  {
    id: 'how-internet-works',
    title: 'How the Internet Works',
    symbol: '🌐',
    pronunciation: '(IN-ter-net)',
    category: 'how-things-work',
    tagline: 'The global invisible web of light pulses, undersea cables, and instant digital letters.',
    analogy: {
      title: 'The Speed-of-Light Digital Mail System',
      story: 'When you tap a video or send a message, your computer breaks it down into millions of tiny numbered puzzle pieces called "data packets". These packets flash as laser pulses through glass fiber-optic cables on the ocean floor, race across continents in milliseconds, and reassemble on your screen!',
      emoji: '⚡'
    },
    howItWorks: {
      title: 'Journey of a Web Page',
      points: [
        'Your Request: When you click a link, your browser asks a Server computer for that page.',
        'Data Packets: The picture and text are sliced into thousands of small digital envelopes.',
        'Fiber-Optic Highways: Flashes of laser light travel through thin glass threads at 186,000 miles per second!',
        'Wi-Fi & Routers: Radio waves beam the packets from your home router into your tablet.'
      ]
    },
    anatomyDiagram: {
      headline: 'Internet Architecture',
      parts: [
        { label: 'Client Device', desc: 'Your tablet, phone, or laptop asking for information.' },
        { label: 'Router & Wi-Fi', desc: 'Turns radio wave signals into internet wire pulses.' },
        { label: 'Undersea Cables', desc: 'Thick fiber-optic cables crossing oceans on the seabed.' },
        { label: 'Data Center / Server', desc: 'Giant buildings filled with computers storing websites and videos.' }
      ]
    },
    funFacts: [
      'Over 99% of all international internet data travels through cables under the ocean, not through satellites!',
      'The first message ever sent on the internet in 1969 was supposed to be "LOGIN", but the system crashed after typing "LO"!',
      'Fiber-optic cables are as thin as a single strand of human hair and carry billions of light signals at once.'
    ],
    kidWords: [
      { word: 'Packet', emoji: '📦', meaning: 'A small chunk of data sent across a computer network.' },
      { word: 'Server', emoji: '🖥️', meaning: 'A powerful computer that stores and serves websites to the world.' },
      { word: 'Fiber-Optic', emoji: '💡', meaning: 'Glass threads that transmit data using pulses of laser light.' }
    ],
    didYouKnowOrigin: 'The internet was invented by computer scientists who wanted to connect research computers so information could survive even if one network cable broke!',
    microQuiz: {
      question: 'How does internet data travel across oceans between countries?',
      options: ['Through giant fiber-optic cables resting on the ocean seabed', 'Carried by carrier pigeons', 'Through underwater sound tubes'],
      correctIndex: 0,
      explanation: 'Over 99% of global internet traffic travels through heavy-duty fiber optic cables on the ocean floor!'
    },
    seeAlso: [
      { id: 'electricity-power', title: 'Electricity', category: 'how-things-work' },
      { id: 'how-cameras-work', title: 'How Cameras Work', category: 'how-things-work' }
    ]
  },
  {
    id: 'how-clocks-work',
    title: 'How Clocks Tell Time',
    symbol: '🕰️',
    pronunciation: '(KLOKS and TYME)',
    category: 'how-things-work',
    tagline: 'The rhythm of swinging pendulums, interlocking gears, and vibrating quartz crystals.',
    analogy: {
      title: 'The Steady Heartbeat of Counting Seconds',
      story: 'Every clock needs a steady "heartbeat" that beats at the exact same rhythm without speeding up or slowing down. In antique grandfather clocks, a swinging pendulum provides the steady tick. In modern digital wristwatches, a tiny quartz crystal vibrates exactly 32,768 times every single second when electric battery power touches it!',
      emoji: '⏱️'
    },
    howItWorks: {
      title: 'Inside a Clock Mechanism',
      points: [
        'The Oscillator (Heartbeat): A pendulum swinging or a quartz crystal vibrating at an unvarying frequency.',
        'The Escapement & Gears: Teeth gears that step forward one tooth with every single tick, turning the second, minute, and hour hands.',
        'The Power Source: A wound-up steel spring or a small chemical coin battery.'
      ]
    },
    funFacts: [
      'The most accurate clocks in the world are atomic clocks that count the vibrations of cesium atoms — they won’t lose 1 second in 300 million years!',
      'Before clocks existed, people told time with sundials using shadows cast by the sun, water clocks, and hourglass sand timers.',
      'There are 86,400 seconds in a single 24-hour day.'
    ],
    kidWords: [
      { word: 'Pendulum', emoji: '⚖️', meaning: 'A hanging weight that swings back and forth at a regular tempo.' },
      { word: 'Gear', emoji: '⚙️', meaning: 'A toothed wheel that interlocks with others to transmit rotational motion.' },
      { word: 'Quartz', emoji: '💎', meaning: 'A common crystal mineral that vibrates with electrical precision.' }
    ],
    didYouKnowOrigin: 'Why does a clock run "clockwise"? Because before mechanical clocks, northern hemisphere sundials had shadows moving from left to right across the top of the dial as the sun moved across the sky!',
    microQuiz: {
      question: 'How many seconds are in one complete minute?',
      options: ['60 seconds', '100 seconds', '10 seconds'],
      correctIndex: 0,
      explanation: 'There are exactly 60 seconds in 1 minute, and 60 minutes in 1 hour!'
    },
    seeAlso: [
      { id: 'wheels-gears', title: 'Wheels & Gears', category: 'how-things-work' },
      { id: 'the-sun', title: 'The Sun', category: 'solar-system' }
    ]
  },
  {
    id: 'wheels-gears',
    title: 'Wheels, Gears & Simple Machines',
    symbol: '⚙️',
    pronunciation: '(WEELZ and GEERZ)',
    category: 'how-things-work',
    tagline: 'The circular inventions that eliminated friction and gave humans mechanical superpowers.',
    analogy: {
      title: 'The Rolling Helpers That Make Heavy Things Light',
      story: 'Trying to drag a heavy boulder across the dirt is exhausting because friction pulls against you. But put that boulder on rolling logs (or a wheeled cart) and suddenly one person can push a 500-pound load with ease! Adding toothed gears lets a kid pedal a bicycle up a steep hill without straining.',
      emoji: '🚲'
    },
    howItWorks: {
      title: 'The 6 Classic Simple Machines',
      points: [
        'The Wheel & Axle: Turns sliding friction into smooth rolling motion.',
        'The Lever (Seesaw): Uses a fulcrum balance point to lift heavy weights with small effort.',
        'The Pulley: Uses ropes and grooved wheels to hoist objects straight up.',
        'The Inclined Plane (Ramp): Lets you push items up gradually instead of lifting straight up.'
      ]
    },
    funFacts: [
      'The wheel was invented over 5,500 years ago in ancient Mesopotamia (originally for spinning clay pottery, then for carts)!',
      'A multi-speed bicycle uses gears of different sizes so you can choose high speed or easy hill climbing.',
      'Can openers, Ferris wheels, escalators, and robot arms all rely on gears intermeshing together.'
    ],
    kidWords: [
      { word: 'Friction', emoji: '🔥', meaning: 'The resistance force created when two surfaces rub together.' },
      { word: 'Fulcrum', emoji: '📐', meaning: 'The pivot or support point on which a lever balances.' },
      { word: 'Axle', emoji: '🦯', meaning: 'The central rod on which a wheel rotates.' }
    ],
    didYouKnowOrigin: 'No animal in nature ever evolved a true spinning wheel and axle on its body, making the wheel one of humanity’s most unique inventions!',
    microQuiz: {
      question: 'What do gears with intermeshing teeth do?',
      options: ['Transfer rotational force and change speed or direction', 'Make wheels square', 'Stop all movement permanently'],
      correctIndex: 0,
      explanation: 'Gears lock their teeth together to multiply force, increase speed, or turn movement around corners!'
    },
    seeAlso: [
      { id: 'how-clocks-work', title: 'How Clocks Tell Time', category: 'how-things-work' },
      { id: 'bridges-engineering', title: 'Bridges & Engineering', category: 'how-things-work' }
    ]
  },
  {
    id: 'electricity-power',
    title: 'Electricity & Circuits',
    symbol: '⚡',
    pronunciation: '(ee-lek-TRIS-ih-tee and SER-kuts)',
    category: 'how-things-work',
    tagline: 'The flowing dance of tiny electrons that lights homes, runs TVs, and powers cities.',
    analogy: {
      title: 'The Water Pipe Loop of Invisible Electrons',
      story: 'Think of electricity like water flowing through a garden hose! The battery is like a water pump pushing electrons forward, the copper wires are like the water pipes, and a lightbulb is like a waterwheel that spins and glows bright as the flowing electrons pass through it!',
      emoji: '💡'
    },
    howItWorks: {
      title: 'The Magic of a Complete Circuit',
      points: [
        'Closed Loop: Electricity can ONLY flow if there is an unbroken circle from the power source back to it.',
        'The Switch: Flipping a light switch simply opens or closes the bridge in the wire loop!',
        'Conductors vs. Insulators: Metals like copper let electricity glide easily (conductors), while rubber and plastic block it safely (insulators).'
      ]
    },
    funFacts: [
      'Electricity travels through copper wires at nearly the speed of light — about 186,000 miles per second!',
      'A single lightning bolt contains enough electrical energy to toast 100,000 slices of bread!',
      'Your own body uses tiny electrical pulses to send signals through your nerves to wiggle your toes and beat your heart.'
    ],
    kidWords: [
      { word: 'Electron', emoji: '⚛️', meaning: 'A tiny negatively charged particle orbiting inside atoms.' },
      { word: 'Circuit', emoji: '🔄', meaning: 'A complete circular loop through which electric current can flow.' },
      { word: 'Conductor', emoji: '🔌', meaning: 'A material (like copper or silver) that allows electricity to flow freely.' }
    ],
    didYouKnowOrigin: 'The word "Electricity" comes from the ancient Greek word "elektron", which meant amber! The Greeks noticed that rubbing amber with wool created static electricity that picked up small feathers.',
    microQuiz: {
      question: 'What happens when you flip a light switch to "OFF"?',
      options: ['It opens a gap in the circuit so electricity stops flowing', 'It empties all electrons out onto the floor', 'It blows out a candle inside'],
      correctIndex: 0,
      explanation: 'Turning a switch off creates an open gap in the circuit loop, stopping electron flow safely!'
    },
    handsOnExperiment: {
      title: 'Static Electricity Balloon Bending Water',
      materials: ['A blown-up latex balloon', 'A piece of wool cloth (or your own clean, dry hair)', 'A gentle trickle of water from a sink faucet'],
      steps: [
        'Rub the balloon vigorously against your hair or wool for 20 seconds to load it with static electrons.',
        'Turn on the sink faucet so a super-thin, smooth stream of water is trickling down.',
        'Bring the rubbed side of the balloon close to the water stream without touching it.',
        'Watch the water stream visibly bend towards the balloon like magic!'
      ],
      explanation: 'The extra negative electrons on the balloon attract the positive side of water molecules, pulling the stream sideways!',
      emoji: '🎈'
    },
    kidTongueTwisterOrRhyme: 'Electric sparks energetically empower every exciting electronic engine!',
    seeAlso: [
      { id: 'lightning-thunder', title: 'Lightning & Thunder', category: 'earth-elements' },
      { id: 'how-internet-works', title: 'How the Internet Works', category: 'how-things-work' }
    ]
  },
  {
    id: 'how-cameras-work',
    title: 'How Cameras Work',
    symbol: '📷',
    pronunciation: '(KAM-er-uhz)',
    category: 'how-things-work',
    tagline: 'How glass lenses and digital sensors capture a fleeting slice of time into a photo.',
    analogy: {
      title: 'Painting with Real Sunlight onto a Grid of Buckets',
      story: 'A camera works just like the human eye! Sunlight bounces off your friend’s smile, enters through a curved glass lens that focuses the rays, and strikes a digital sensor chip covered in millions of tiny light-catcher buckets (pixels). Each pixel measures how much red, green, and blue light landed in its bucket!',
      emoji: '🖼️'
    },
    howItWorks: {
      title: 'Key Steps of Taking a Photo',
      points: [
        'The Aperture (Pupil): The adjustable opening that controls how much light enters the camera.',
        'The Shutter (Eyelid): A super-fast door that opens for 1/1000th of a second to freeze action without blur.',
        'The Sensor (Retina): A silicon chip made of millions of color-sensitive pixels that converts light into numbers.'
      ]
    },
    funFacts: [
      'The first photograph ever taken in 1826 required an 8-hour exposure in bright sunlight to show a courtyard view!',
      'Your phone’s camera sensor can record over 48 million pixels in a single snap.',
      'The word "Photography" literally means "Drawing with Light" in Greek ("photo" = light, "graph" = drawing).'
    ],
    kidWords: [
      { word: 'Pixel', emoji: '🟩', meaning: 'The tiny color dots that combine on a screen to form a full photo.' },
      { word: 'Aperture', emoji: '⭕', meaning: 'The circular opening in a lens that adjusts how much light enters.' },
      { word: 'Shutter', emoji: '🚪', meaning: 'The rapid mechanical door that opens and closes to expose light to the sensor.' }
    ],
    didYouKnowOrigin: 'Before digital chips, cameras used plastic film coated with light-sensitive silver salt crystals that had to be bathed in darkroom chemicals to reveal pictures!',
    microQuiz: {
      question: 'What does the Greek word "Photography" literally translate to?',
      options: ['Drawing with Light', 'Magic Mirror', 'Talking to Robots'],
      correctIndex: 0,
      explanation: '"Photo" means light and "graphy" means drawing or writing — literally drawing pictures with light rays!'
    },
    seeAlso: [
      { id: 'five-senses', title: 'The 5 Senses (Sight)', category: 'human-body' },
      { id: 'how-internet-works', title: 'How the Internet Works', category: 'how-things-work' }
    ]
  },
  {
    id: 'bridges-engineering',
    title: 'How Giant Bridges Stay Up',
    symbol: '🌉',
    pronunciation: '(BRIJ-ez and en-juh-NEER-ing)',
    category: 'how-things-work',
    tagline: 'The physics of suspension cables, concrete arches, and triangular trusses spanning wide rivers.',
    analogy: {
      title: 'The Tug-of-War Balance Across the Water',
      story: 'When thousands of heavy cars drive across a long suspension bridge (like the Golden Gate Bridge), how does it not collapse? Giant steel cables as thick as telephone poles pull upward with immense tension, anchoring into massive bedrock concrete blocks on the shores that hold everything steady in a giant, beautiful tug-of-war!',
      emoji: '🏗️'
    },
    howItWorks: {
      title: 'The 3 Main Bridge Designs',
      points: [
        'Beam & Truss Bridges: Use rigid interlocking triangles (trusses) because triangles cannot deform or fold under pressure!',
        'Arch Bridges: Squeeze weight down into the ground curves (compression), used by Romans 2,000 years ago.',
        'Suspension Bridges: Hang the roadway from curving vertical steel wire ropes anchored to tall tower piers.'
      ]
    },
    funFacts: [
      'The longest sea-crossing bridge in the world is the Hong Kong–Zhuhai–Macau Bridge — 34 miles long with an undersea tunnel!',
      'Triangles are the strongest geometric shape in engineering because all three sides support every push together.',
      'Roman aqueduct arch bridges built without any cement or glue are still standing and carrying water today after 2,000 years.'
    ],
    kidWords: [
      { word: 'Tension', emoji: '🪢', meaning: 'A pulling or stretching force in a rope or cable.' },
      { word: 'Compression', emoji: '🗜️', meaning: 'A squeezing or pushing-together force.' },
      { word: 'Truss', emoji: '📐', meaning: 'A rigid framework made of connected structural triangles.' }
    ],
    didYouKnowOrigin: 'The steel wire cables holding up the Brooklyn Bridge in New York were spun on site wire-by-wire in 1883 and stretch over 14,000 miles if laid out end-to-end!',
    microQuiz: {
      question: 'Which geometric shape is the strongest and most rigid for building bridges and towers?',
      options: ['Triangle', 'Square', 'Circle'],
      correctIndex: 0,
      explanation: 'Triangles are structurally rigid: you cannot bend a corner without changing the length of a side!'
    },
    handsOnExperiment: {
      title: 'The Paper Bridge Strength Test',
      materials: ['2 stacked books of equal height', 'A sheet of paper', 'Pennies or small coins'],
      steps: [
        'Place the two books 4 inches apart.',
        'Lay a flat sheet of paper across the gap as a bridge. Place pennies on it — it collapses with just 2 or 3 pennies!',
        'Now accordion-fold another sheet of paper into tight zig-zag triangular ridges (corrugated shape) and lay it across the gap.',
        'Stack pennies on it: The folded paper bridge can now hold 30+ pennies without falling!'
      ],
      explanation: 'The folds create a series of rigid triangles that distribute weight sideways across the book supports!',
      emoji: '🪙'
    },
    seeAlso: [
      { id: 'geometric-shapes', title: 'Shapes & Geometry', category: 'numbers' },
      { id: 'wheels-gears', title: 'Wheels & Gears', category: 'how-things-work' }
    ]
  },
  {
    id: 'submarines-diving',
    title: 'How Submarines Dive & Float',
    symbol: '🤿',
    pronunciation: '(SUB-muh-reenz and DYE-ving)',
    category: 'how-things-work',
    tagline: 'Controlling buoyancy with giant water ballast tanks to explore the deep ocean abyss.',
    analogy: {
      title: 'The Swimming Balloon with Built-in Water Tanks',
      story: 'A submarine can choose when to float like a cork or sink like a stone! It has giant hollow ballast tanks between its hulls. When it wants to dive, valves open to let heavy ocean water rush in, pulling the submarine deep down. To rise back to the sunlight, blasts of high-pressure air shoot the water out!',
      emoji: '⚓'
    },
    howItWorks: {
      title: 'The Physics of Buoyancy',
      points: [
        'Surface Mode: Ballast tanks are filled with light air — the submarine floats high on ocean waves.',
        'Diving Mode: Flood gates open at the bottom, vents open at the top, and heavy sea water fills the tanks.',
        'Surfacing: Compressed air tanks blast pressurized air into the ballast tanks, blowing water back out through the bottom.'
      ]
    },
    funFacts: [
      'Some scientific research submarines can dive nearly 36,000 feet down to the bottom of the Mariana Trench!',
      'Nuclear submarines make their own fresh drinking water and oxygen from seawater, staying submerged for months without surfacing.',
      'Submarines use Sonar (sound echoes) to navigate in pitch-black deep waters without hitting underwater mountains.'
    ],
    kidWords: [
      { word: 'Buoyancy', emoji: '🛟', meaning: 'The upward force that makes objects float in water or air.' },
      { word: 'Ballast', emoji: '🪨', meaning: 'Heavy material or water placed in tanks to control balance and depth.' },
      { word: 'Sonar', emoji: '🔊', meaning: 'Using sound wave echoes to detect underwater objects.' }
    ],
    didYouKnowOrigin: 'The first working military submarine, called "The Turtle", was invented in 1775 and was made of hand-carved oak wood shaped like a giant egg and powered by foot pedals!',
    microQuiz: {
      question: 'What do submarines fill their ballast tanks with when they want to surface back up to the air?',
      options: ['High-pressure compressed air', 'Heavy rocks', 'More sea water'],
      correctIndex: 0,
      explanation: 'Blowing compressed air into the tanks pushes out heavy water, making the submarine buoyant enough to float up!'
    },
    seeAlso: [
      { id: 'world-oceans', title: 'World Oceans', category: 'countries-world' },
      { id: 'water-element', title: 'Water (H2O)', category: 'earth-elements' }
    ]
  },
  {
    id: 'smartphones-touchscreens',
    title: 'Smartphones & Touchscreens',
    symbol: '📱',
    pronunciation: '(SMAHRT-fohnz and TUCH-skreenz)',
    category: 'how-things-work',
    tagline: 'Pocket glass supercomputers that sense your finger’s natural electric charge.',
    analogy: {
      title: 'The Invisible Electric Grid on Glass',
      story: 'How does your phone screen know exactly where you tapped without any buttons? The smooth glass is coated with an invisible grid of transparent electrical wires! Your human body is naturally full of tiny electric charges. When your finger touches the glass, it absorbs a tiny bit of electricity from the grid, and the computer chip calculates the exact X-and-Y pixel coordinate in milliseconds!',
      emoji: '⚡'
    },
    howItWorks: {
      title: 'Capacitive Touch & Silicon Brains',
      points: [
        'Capacitive Glass Grid: An invisible grid of indium tin oxide lines holds a steady electric voltage across the glass.',
        'Finger Distortion: Your fingertip draws a microscopic electrical charge, altering the local electrostatic field.',
        'Microprocessor Magic: The phone’s processor recalculates your touch location 120 times every second, letting you swipe, pinch-to-zoom, and scroll smoothly.'
      ]
    },
    funFacts: [
      'The smartphone in your pocket has over 100,000 times more computing power than the guidance computer NASA used to land Apollo 11 astronauts on the Moon!',
      'Why don’t touchscreens work with regular winter gloves? Because thick cloth blocks your finger’s natural electrical charge from reaching the glass!',
      'A typical phone screen packs over 2 to 3 million microscopic red, green, and blue LED subpixels glowing together.'
    ],
    kidWords: [
      { word: 'Capacitive', emoji: '⚡', meaning: 'Using electrostatic field changes to detect touch.' },
      { word: 'Processor', emoji: '🧠', meaning: 'The microscopic electronic chip that executes program instructions.' },
      { word: 'Pixel', emoji: '🔲', meaning: 'A tiny illuminated dot on a display screen that combines with millions of others to form an image.' }
    ],
    didYouKnowOrigin: 'The first finger-touchscreen concept was invented in 1965 by British engineer E.A. Johnson for air traffic control displays!',
    microQuiz: {
      question: 'Why does your finger make a smartphone touchscreen respond when you tap it?',
      options: ['Your skin conducts a tiny natural electric charge that changes the screen’s field', 'Your finger is very heavy', 'The glass has tiny buttons'],
      correctIndex: 0,
      explanation: 'Human skin carries a small electric charge that disturbs the screen’s capacitive grid, allowing the processor to track your finger!'
    },
    seeAlso: [
      { id: 'how-internet-works', title: 'How the Internet Works', category: 'how-things-work' },
      { id: 'electricity-power', title: 'Electricity', category: 'how-things-work' }
    ]
  },
  {
    id: 'electric-cars-batteries',
    title: 'Electric Cars & Rechargeable Batteries',
    symbol: '🚗',
    pronunciation: '(ee-LEK-trik KARZ and BAT-er-eez)',
    category: 'how-things-work',
    tagline: 'Quiet, zero-exhaust vehicles powered by billions of dancing lithium ions and electromagnetic motors.',
    analogy: {
      title: 'The Giant Remote-Controlled Car You Can Ride In',
      story: 'An electric car is like a giant, comfortable RC toy car powered by a massive skateboard of rechargeable battery cells! Instead of burning noisy gasoline in hot explosive pistons, an electric car uses magnets and copper coils to spin electric motors silently with instant rocket acceleration — with zero tailpipe smoke!',
      emoji: '🔋'
    },
    howItWorks: {
      title: 'How Electric Vehicles Move',
      points: [
        'Lithium-Ion Battery Pack: Thousands of battery cells under the car floor store electrical energy through chemical reactions.',
        'Electric Induction Motor: Magnetic fields created by alternating electric currents spin a metal rotor that turns the car wheels directly.',
        'Regenerative Braking: When you take your foot off the accelerator, the motor reverses into a generator, slowing the car down while pumping electric energy BACK into the battery!'
      ]
    },
    funFacts: [
      'Electric motors have only ONE major moving part (the rotor), while gasoline engines have over 200 moving parts that need motor oil and spark plugs!',
      'Electric cars can accelerate faster than many supercars because electric motors deliver maximum torque instantly at 0 RPM.',
      'Regenerative braking saves so much energy that electric car brake pads can last over 100,000 miles without wearing out.'
    ],
    kidWords: [
      { word: 'Lithium', emoji: '🔋', meaning: 'The lightest metallic element, ideal for storing dense electrical energy in rechargeable batteries.' },
      { word: 'Torque', emoji: '⚙️', meaning: 'The twisting rotational force that gets wheels spinning quickly.' },
      { word: 'Regenerative', emoji: '♻️', meaning: 'Recovering and reusing energy that would otherwise be wasted as friction heat.' }
    ],
    didYouKnowOrigin: 'Electric cars are not new! In the year 1900, about 38% of all automobiles in the United States were electric, but cheap gasoline later took over until modern lithium batteries brought them back!',
    microQuiz: {
      question: 'What happens when an electric car steps on its regenerative brakes?',
      options: ['The electric motor acts as a generator and recharges the battery with kinetic energy', 'The battery turns off completely', 'The wheels blow steam'],
      correctIndex: 0,
      explanation: 'Regenerative braking captures the car’s forward rolling momentum and turns it back into stored electricity for the battery!'
    },
    seeAlso: [
      { id: 'solar-panels-energy', title: 'Solar Panels & Energy', category: 'how-things-work' },
      { id: 'magnets-magnetism', title: 'Magnets & Magnetism', category: 'how-things-work' }
    ]
  },
  {
    id: 'solar-panels-energy',
    title: 'Solar Panels & Clean Energy',
    symbol: '☀️',
    pronunciation: '(SOH-ler PAN-ulz and EN-er-jee)',
    category: 'how-things-work',
    tagline: 'Silicon wafer sandwiches catching sunlight photons and knocking electrons into electric currents.',
    analogy: {
      title: 'The Sunlight Catcher and Electron Pinball Machine',
      story: 'Imagine rays of golden sunlight like trillions of tiny bouncing ping-pong balls of energy called Photons. When photons strike a dark blue solar panel on your roof, they slam into silicon atoms and knock loose tiny electric electrons like a pinball machine! Those loose electrons flow through copper wires as clean, fresh electricity to power your television and refrigerator!',
      emoji: '⚡'
    },
    howItWorks: {
      title: 'The Photovoltaic (PV) Effect',
      points: [
        'Silicon Layers: Panels are made of two specially treated layers of purified silicon (N-type with extra electrons, P-type with holes).',
        'Photon Strike: Sunlight packets knock electrons free across the electric boundary junction.',
        'Inverter Conversion: Solar panels generate Direct Current (DC) electricity; a wall inverter converts it into Alternating Current (AC) for household wall plugs.'
      ]
    },
    funFacts: [
      'Enough sunlight strikes planet Earth in just ONE HOUR to power the entire human civilization for a whole year!',
      'Solar panels have no moving parts, generate zero noise, and can produce clean electricity for 25 to 30 years with just occasional rain to wash off dust.',
      'The International Space Station has giant solar wings stretching 240 feet wide that continuously rotate to track the Sun.'
    ],
    kidWords: [
      { word: 'Photon', emoji: '✨', meaning: 'A discrete packet or quantum of light energy travelling at light speed.' },
      { word: 'Photovoltaic', emoji: '🔆', meaning: 'Relating to the direct production of electric current at the junction of two materials exposed to light.' },
      { word: 'Inverter', emoji: '🔌', meaning: 'An electrical device that converts direct current (DC) into alternating current (AC).' }
    ],
    didYouKnowOrigin: 'French physicist Edmond Becquerel discovered the photovoltaic effect in 1839 when he was just 19 years old while experimenting in his father’s laboratory!',
    microQuiz: {
      question: 'What material are most modern solar panels manufactured from?',
      options: ['Purified Silicon (found abundantly in ordinary quartz sand!)', 'Solid plastic', 'Cardboard paper'],
      correctIndex: 0,
      explanation: 'Solar cells are made from silicon crystals, the second most abundant element in Earth’s crust, refined from silica sand!'
    },
    seeAlso: [
      { id: 'the-sun', title: 'The Sun', category: 'solar-system' },
      { id: 'electricity-power', title: 'Electricity', category: 'how-things-work' }
    ]
  },
  {
    id: 'magnets-magnetism',
    title: 'Magnets & Magnetic Fields',
    symbol: '🧲',
    pronunciation: '(MAG-nits and MAG-nuh-tiz-um)',
    category: 'how-things-work',
    tagline: 'Invisible force fields with North and South poles that attract steel, guide compasses, and float bullet trains.',
    analogy: {
      title: 'The Invisible Tractor Beam and Magic Repelling Cushion',
      story: 'Have you ever tried pushing two identical magnets together and felt an invisible, bouncy rubber cushion pushing back? Every magnet has a North pole and a South pole. Opposites attract (North loves South and snaps tight!), while likes repel (North pushes North away). Earth itself is a gigantic magnet with an invisible magnetic umbrella shielding us from space!',
      emoji: '🧭'
    },
    howItWorks: {
      title: 'How Magnetic Domains Work',
      points: [
        'Atomic Alignment: In magnetic metals like iron, nickel, and cobalt, trillions of microscopic atomic spinning electrons line up in the exact same direction (magnetic domains).',
        'Invisible Field Lines: Force loops flow out from the North pole and curve back into the South pole.',
        'Electromagnets: Running an electric current through a coiled copper wire creates an instant magnet that can be switched ON and OFF with a flip of a switch!'
      ]
    },
    funFacts: [
      'Maglev (Magnetic Levitation) bullet trains in Japan float 4 inches above the tracks on magnetic fields and travel at over 370 miles per hour with zero friction!',
      'Homing pigeons and sea turtles have microscopic magnetic crystals in their beaks and brains that act like built-in GPS compasses to navigate across thousands of miles.',
      'If you cut a bar magnet in half, you don’t get a North piece and a South piece — you instantly get TWO smaller complete magnets, each with its own North and South poles!'
    ],
    kidWords: [
      { word: 'Attract', emoji: '🧲', meaning: 'To exert a pulling force that draws unlike poles together.' },
      { word: 'Repel', emoji: '↔️', meaning: 'To exert a pushing force that forces like magnetic poles apart.' },
      { word: 'Electromagnet', emoji: '⚡', meaning: 'A soft metal core made into a magnet by the passage of electric current through a surrounding coil.' }
    ],
    didYouKnowOrigin: 'Magnets were discovered over 2,500 years ago in ancient Greece in a region called Magnesia, where people found black stones (lodestones) that magically pulled iron needles!',
    microQuiz: {
      question: 'What happens when you bring the North pole of one magnet close to the North pole of another magnet?',
      options: ['They push each other away (repel)', 'They stick tightly like glue', 'They turn into water'],
      correctIndex: 0,
      explanation: 'Like magnetic poles (North & North or South & South) always repel each other, while opposite poles attract!'
    },
    handsOnExperiment: {
      title: 'Build a Floating Water Compass',
      materials: ['A metal sewing needle', 'A refrigerator magnet', 'A slice of wine cork or foam leaf', 'A shallow bowl of water'],
      steps: [
        'Rub the needle 30 times in one direction against one pole of your refrigerator magnet to magnetize it.',
        'Carefully lay the needle flat on top of the small floating cork slice in the center of the water bowl.',
        'Watch the floating cork slowly spin by itself until it stops pointing directly along the Earth’s North-South magnetic axis!',
        'Compare with a phone compass: You built an ancient working navigation instrument!'
      ],
      explanation: 'The magnetized needle aligns with planet Earth’s natural geomagnetic field lines!',
      emoji: '🧭'
    },
    seeAlso: [
      { id: 'planet-earth', title: 'Planet Earth', category: 'solar-system' },
      { id: 'auroras-northern-lights', title: 'Northern Lights', category: 'earth-elements' }
    ]
  },
  {
    id: 'microscopes-telescopes',
    title: 'Microscopes & Optical Lenses',
    symbol: '🔬',
    pronunciation: '(MY-kruh-skohps and OP-tih-kul LEN-zez)',
    category: 'how-things-work',
    tagline: 'Curved glass domes that bend light rays to zoom into single cells or faraway galaxies.',
    analogy: {
      title: 'The Light-Bending Glass Magic Looking Glasses',
      story: 'Glass can bend light rays like a funhouse mirror! A curved glass lens (thicker in the middle) bends spreading light rays together into your pupil, making microscopic things like an ant’s eyelashes or bacteria look thousands of times bigger than they really are!',
      emoji: '🔍'
    },
    howItWorks: {
      title: 'Refraction & Magnification',
      points: [
        'Refraction: Light travels slower through dense glass than through air, causing light rays to bend at an angle when entering a curved lens.',
        'Convex Lenses: Thicker in the center; focus light rays inward to a focal point to magnify images.',
        'Compound Microscopes: Use an objective lens close to the slide and an eyepiece lens close to your eye, multiplying zoom power up to 2,000x!'
      ]
    },
    funFacts: [
      'Dutch draper Antonie van Leeuwenhoek looked through his handcrafted single-lens microscope in 1674 and became the first human ever to see living bacteria, which he called "animalcules"!',
      'Electron Microscopes don’t use light at all — they shoot beams of electrons, magnifying objects up to 10,000,000 times to see individual DNA strands!',
      'Water droplets act like natural magnifying lenses: place a drop of water on a newspaper letter and watch the font grow huge!'
    ],
    kidWords: [
      { word: 'Refraction', emoji: '📐', meaning: 'The bending of a light wave when it passes from one transparent medium to another.' },
      { word: 'Convex', emoji: '🔍', meaning: 'Curving outward like the exterior of a circle or sphere.' },
      { word: 'Magnification', emoji: '🔬', meaning: 'The process of enlarging the apparent visual size of something.' }
    ],
    didYouKnowOrigin: 'The word "Microscope" comes from two Greek words: "Mikros" (meaning small) and "Skopein" (meaning to look or see) — literally "to look at small things"!',
    microQuiz: {
      question: 'What happens to a beam of light when it passes from air into a curved glass lens?',
      options: ['It slows down and bends (refraction)', 'It turns completely black', 'It disappears into smoke'],
      correctIndex: 0,
      explanation: 'Because glass is denser than air, light slows down and bends at an angle, focusing the rays to magnify the image!'
    },
    seeAlso: [
      { id: 'james-webb-telescope', title: 'Webb Telescope', category: 'solar-system' },
      { id: 'human-eyes', title: 'Eyes & Vision', category: 'human-body' }
    ]
  },
  {
    id: 'cameras-photography',
    title: 'Cameras & Photography',
    symbol: '📷',
    pronunciation: '(KAM-er-uhz and foh-TOG-ruh-fee)',
    category: 'how-things-work',
    tagline: 'Trapping moments of light through lenses, shutters, and millions of digital pixel sensors.',
    analogy: {
      title: 'Painting with Light in a Blink of an Eye',
      story: 'A camera works almost identically to your own human eye! Light bounces off a smiling face, travels through a curved lens (the cornea), passes through an opening iris ring (aperture), and hits a digital sensor chip (retina) that records millions of tiny colored dots in a 1/1000th-of-a-second blink (shutter)!',
      emoji: '📸'
    },
    howItWorks: {
      title: 'The Exposure Triangle',
      points: [
        'Aperture (f-stop): The circular iris opening that controls how much light passes into the camera body.',
        'Shutter Speed: The high-speed mechanical curtain that opens and closes in fractions of a second to freeze motion.',
        'Digital Sensor (ISO): A grid of millions of light-sensitive photodiodes (pixels) that turn light into digital color numbers.'
      ]
    },
    funFacts: [
      'The word "Photography" literally means "Drawing with Light" in Greek!',
      'The very first permanent photograph in human history was taken in 1826 by Joseph Nicéphore Niépce in France — and required an 8-hour exposure!',
      'Today, humans take over 5 billion digital photographs every single day on smartphones!'
    ],
    kidWords: [
      { word: 'Aperture', emoji: '⭕', meaning: 'The adjustable opening in a lens through which light passes to the sensor.' },
      { word: 'Shutter', emoji: '🚪', meaning: 'A mechanical curtain that opens for a set duration to expose the sensor to light.' },
      { word: 'Sensor', emoji: '🔲', meaning: 'An electronic chip covered in photodiodes that converts photons into digital electrical signals.' }
    ],
    didYouKnowOrigin: 'The earliest ancestor of the camera was the "Camera Obscura" (Latin for "Dark Chamber"), an ancient dark room with a tiny pinhole that projected an upside-down live image of the outside world onto the wall!',
    microQuiz: {
      question: 'What does the word "Photography" literally mean in ancient Greek?',
      options: ['Drawing or Writing with Light', 'Magic paper', 'Freeze time'],
      correctIndex: 0,
      explanation: 'From "Photo" (Light) and "Graph" (Drawing/Writing) — photography literally means painting or drawing with light rays!'
    },
    seeAlso: [
      { id: 'human-eyes', title: 'Eyes & Vision', category: 'human-body' },
      { id: 'smartphones-touchscreens', title: 'Smartphones & Touchscreens', category: 'how-things-work' }
    ]
  },
  {
    id: 'robots-ai',
    title: 'Robots & Artificial Intelligence',
    symbol: '🤖',
    pronunciation: '(ROH-bots and ahr-tuh-FISH-ul in-TEL-ih-jens)',
    category: 'how-things-work',
    tagline: 'Sensors, motors, microchips, and algorithms helping machines see, learn, and perform tasks.',
    analogy: {
      title: 'The Computer with Senses and Mechanical Muscles',
      story: 'A robot is a computer that can physically interact with the real world! It has sensors (cameras for eyes, ultrasonic microphones for ears), computer chips for a brain, and electric motors and hydraulic gears for muscles. Artificial Intelligence (AI) is the software code that lets machines recognize patterns, learn from examples, and make smart decisions!',
      emoji: '🧠'
    },
    howItWorks: {
      title: 'The 3 Main Parts of Any Robot',
      points: [
        'Sensors (Perception): Cameras, lidar lasers, gyroscopes, and touch bumpers that gather data about the environment.',
        'Controller / Computer Brain: Processes sensor inputs and calculates the best movement or answer based on algorithms.',
        'Actuators (Action): Electric motors, servos, and wheels that physically move robotic arms, legs, or wheels.'
      ]
    },
    funFacts: [
      'NASA’s Perseverance and Curiosity rovers are autonomous robotic geologists driving across the red deserts of Mars right now!',
      'The word "Robot" was coined in 1920 in a Czech play by Karel Čapek, derived from "robota" meaning forced work or labor.',
      'Surgical robots help human doctors perform delicate brain and heart operations through incisions smaller than a pencil tip!'
    ],
    kidWords: [
      { word: 'Actuator', emoji: '🦾', meaning: 'A mechanical device for moving or controlling a mechanism or robotic joint.' },
      { word: 'Algorithm', emoji: '📝', meaning: 'A step-by-step set of mathematical instructions for solving a problem.' },
      { word: 'Autonomous', emoji: '🛸', meaning: 'Able to navigate and perform operations independently without direct human remote control.' }
    ],
    didYouKnowOrigin: 'The robotic Mars rover Curiosity was programmed to sing "Happy Birthday" to itself on Mars on its first anniversary in August 2013 using vibrations in its soil analysis instrument!',
    microQuiz: {
      question: 'What do we call the mechanical motors and robotic joints that allow a robot to move its arms and wheels?',
      options: ['Actuators', 'Antennas', 'Sensors'],
      correctIndex: 0,
      explanation: 'Actuators are the motors, pistons, and servos that convert electrical energy into physical robotic movement!'
    },
    seeAlso: [
      { id: 'how-internet-works', title: 'The Internet', category: 'how-things-work' },
      { id: 'astronauts-rockets', title: 'Astronauts & Rockets', category: 'solar-system' }
    ]
  },
  {
    id: 'refrigerators-cooling',
    title: 'Refrigerators & Air Conditioners',
    symbol: '❄️',
    pronunciation: '(ree-FRIJ-er-ay-terz and AIR kun-DISH-un-ing)',
    category: 'how-things-work',
    tagline: 'How circulating coolant pumps heat OUT of your milk and home to make things icy cold.',
    analogy: {
      title: 'The Heat-Stealing Sponge and Evaporator Pump',
      story: 'A refrigerator doesn’t actually "create cold" — it STEALS HEAT and throws it outside! Think of coolant liquid inside the metal pipes like a magic sponge. As it flows inside the fridge, it absorbs heat from your apples and milk and evaporates into gas. Then a noisy compressor pumps that gas outside to the back of the fridge, squeezing the heat out into your kitchen room!',
      emoji: '🧃'
    },
    howItWorks: {
      title: 'The Refrigeration Vapor-Compression Cycle',
      points: [
        'Expansion Valve: Coolant liquid drops in pressure and becomes freezing cold as it enters inside evaporator coils.',
        'Evaporator (Heat Absorption): The icy liquid absorbs heat from inside the fridge, boiling into a warm gas.',
        'Compressor (The Pump): Squeezes the gas, raising its temperature and pressure.',
        'Condenser (Heat Release): Hot coils on the back/bottom release the stolen heat into the room air, turning coolant back into a liquid to repeat the cycle!'
      ]
    },
    funFacts: [
      'If you touch the metal coils on the back or bottom of a running refrigerator, you will feel warm air — that is the heat stolen from your ice cream!',
      'Before electric refrigerators were invented in the 1920s, people stored food in wooden "iceboxes" filled with giant blocks of lake ice cut during winter and delivered by horse wagons!',
      'Air conditioners in cars and homes work using the exact same four-step refrigeration cycle.'
    ],
    kidWords: [
      { word: 'Refrigerant', emoji: '🧪', meaning: 'A fluid with a very low boiling point that circulates to absorb and transfer heat.' },
      { word: 'Compressor', emoji: '⚙️', meaning: 'A mechanical pump that squeezes gas coolant into a high-pressure state.' },
      { word: 'Condenser', emoji: '♨️', meaning: 'Coils where hot vapor gives off heat and condenses back into liquid.' }
    ],
    didYouKnowOrigin: 'If you leave the refrigerator door open, will it cool down your kitchen? No! Because the compressor motor generates more heat in the back than the open door cools in the front, leaving the door open actually makes the room hotter!',
    microQuiz: {
      question: 'How does a refrigerator keep milk and food cold inside?',
      options: ['It absorbs heat from inside and pumps it out into the room air behind it', 'It manufactures ice from air', 'It blows winter wind from a freezer box'],
      correctIndex: 0,
      explanation: 'Refrigerators use circulating refrigerant fluid to absorb heat from food and expel it into the room through rear condenser coils!'
    },
    seeAlso: [
      { id: 'water-element', title: 'Water Cycle', category: 'earth-elements' },
      { id: 'electricity-power', title: 'Electricity', category: 'how-things-work' }
    ]
  }
];
