import { EncyclopediaEntry } from '../../types';

export const HOW_THINGS_WORK_ENTRIES: EncyclopediaEntry[] = [
  {
    id: 'how-airplanes-fly',
    title: 'How Airplanes Fly (Aerodynamics)',
    symbol: '✈️',
    pronunciation: '(AIR-playnz and EHR-oh-die-NAM-iks)',
    category: 'how-things-work',
    tagline: 'How a 500-ton metal jet lifts gracefully into the blue sky using invisible air pressure.',
    analogy: {
      title: 'Water-Skiing on an Ocean of Air',
      story: 'You can’t see air, but it is made of trillions of tiny molecules! An airplane wing is curved on top and flat on the bottom (an airfoil shape). As the plane zooms forward, air has to race faster over the curved top, creating low pressure that sucks the plane up into the sky, just like water lifts a surfboard!',
      emoji: '🪁'
    },
    howItWorks: {
      title: 'The 4 Forces of Flight',
      points: [
        'Lift (Upward): Created by air rushing over specially curved wings (Bernoulli’s principle).',
        'Weight/Gravity (Downward): The downward pull of Earth’s gravity that wings must overcome.',
        'Thrust (Forward): The powerful push created by jet engines sucking air and blasting it back.',
        'Drag (Backward): The wind resistance trying to slow the aircraft down.'
      ]
    },
    anatomyDiagram: {
      headline: 'Parts of an Airplane',
      parts: [
        { label: 'Airfoil Wings', desc: 'Generate upward aerodynamic lift.' },
        { label: 'Jet Engines', desc: 'Create forward thrust by burning fuel with compressed air.' },
        { label: 'Rudder (Tail)', desc: 'Turns the nose left or right (yaw).' },
        { label: 'Elevators (Tail)', desc: 'Point the nose up to climb or down to descend (pitch).' }
      ]
    },
    funFacts: [
      'A Boeing 747 airplane has about 6 million individual parts assembled together!',
      'Commercial jets fly around 35,000 feet high where the air is thinner, using less fuel to glide faster.',
      'The Wright Brothers made the first powered airplane flight in 1903 — and it lasted only 12 seconds!'
    ],
    kidWords: [
      { word: 'Lift', emoji: '🛫', meaning: 'The upward aerodynamic force that opposes gravity and keeps planes in the sky.' },
      { word: 'Thrust', emoji: '🚀', meaning: 'The forward push generated by engines.' },
      { word: 'Airfoil', emoji: '🪶', meaning: 'The curved cross-section shape of a wing designed to create lift.' }
    ],
    didYouKnowOrigin: 'Birds provided the original blueprint for flight! Engineers studied how eagles curve their feathers to glide on thermal air currents without flapping.',
    microQuiz: {
      question: 'Which of the 4 flight forces lifts the airplane up into the clouds?',
      options: ['Lift', 'Gravity', 'Drag'],
      correctIndex: 0,
      explanation: 'Lift is created by the curved shape of wings moving through air, overcoming gravity!'
    },
    handsOnExperiment: {
      title: 'The Paper Strip Bernoulli Lift Trick',
      materials: ['A strip of paper about 2 inches wide and 8 inches long'],
      steps: [
        'Hold the short edge of the paper strip just under your bottom lip with both hands.',
        'Notice how the long end of the paper droops down towards the floor.',
        'Blow a steady, fast stream of air over the TOP curve of the paper.',
        'Watch in amazement as the droopy paper instantly rises straight up like magic!'
      ],
      explanation: 'Fast-moving air over the top creates lower pressure, and higher air pressure underneath pushes the paper up — the exact same way airplane wings work!',
      emoji: '📄'
    },
    kidTongueTwisterOrRhyme: 'Fast flying planes glide freely floating through fluffy foggy clouds!',
    seeAlso: [
      { id: 'air-element', title: 'Air & Atmosphere', category: 'earth-elements' },
      { id: 'letter-a', title: 'Letter A', category: 'alphabets' }
    ]
  },
  {
    id: 'how-internet-works',
    title: 'How the Internet Works',
    symbol: '🌐',
    pronunciation: '(IN-ter-net)',
    category: 'how-things-work',
    tagline: 'The global invisible web of light pulses, undersea cables, and instant digital letters.',
    analogy: {
      title: 'The Speed-of-Light Digital Mail System',
      story: 'When you tap a video or send a message, your computer breaks it down into millions of tiny numbered puzzle pieces called "data packets". These packets flash as laser pulses through glass fiber-optic cables on the ocean floor, race across continents in milliseconds, and reassemble on your screen!',
      emoji: '⚡'
    },
    howItWorks: {
      title: 'Journey of a Web Page',
      points: [
        'Your Request: When you click a link, your browser asks a Server computer for that page.',
        'Data Packets: The picture and text are sliced into thousands of small digital envelopes.',
        'Fiber-Optic Highways: Flashes of laser light travel through thin glass threads at 186,000 miles per second!',
        'Wi-Fi & Routers: Radio waves beam the packets from your home router into your tablet.'
      ]
    },
    anatomyDiagram: {
      headline: 'Internet Architecture',
      parts: [
        { label: 'Client Device', desc: 'Your tablet, phone, or laptop asking for information.' },
        { label: 'Router & Wi-Fi', desc: 'Turns radio wave signals into internet wire pulses.' },
        { label: 'Undersea Cables', desc: 'Thick fiber-optic cables crossing oceans on the seabed.' },
        { label: 'Data Center / Server', desc: 'Giant buildings filled with computers storing websites and videos.' }
      ]
    },
    funFacts: [
      'Over 99% of all international internet data travels through cables under the ocean, not through satellites!',
      'The first message ever sent on the internet in 1969 was supposed to be "LOGIN", but the system crashed after typing "LO"!',
      'Fiber-optic cables are as thin as a single strand of human hair and carry billions of light signals at once.'
    ],
    kidWords: [
      { word: 'Packet', emoji: '📦', meaning: 'A small chunk of data sent across a computer network.' },
      { word: 'Server', emoji: '🖥️', meaning: 'A powerful computer that stores and serves websites to the world.' },
      { word: 'Fiber-Optic', emoji: '💡', meaning: 'Glass threads that transmit data using pulses of laser light.' }
    ],
    didYouKnowOrigin: 'The internet was invented by computer scientists who wanted to connect research computers so information could survive even if one network cable broke!',
    microQuiz: {
      question: 'How does internet data travel across oceans between countries?',
      options: ['Through giant fiber-optic cables resting on the ocean seabed', 'Carried by carrier pigeons', 'Through underwater sound tubes'],
      correctIndex: 0,
      explanation: 'Over 99% of global internet traffic travels through heavy-duty fiber optic cables on the ocean floor!'
    },
    seeAlso: [
      { id: 'electricity-power', title: 'Electricity', category: 'how-things-work' },
      { id: 'how-cameras-work', title: 'How Cameras Work', category: 'how-things-work' }
    ]
  },
  {
    id: 'how-clocks-work',
    title: 'How Clocks Tell Time',
    symbol: '🕰️',
    pronunciation: '(KLOKS and TYME)',
    category: 'how-things-work',
    tagline: 'The rhythm of swinging pendulums, interlocking gears, and vibrating quartz crystals.',
    analogy: {
      title: 'The Steady Heartbeat of Counting Seconds',
      story: 'Every clock needs a steady "heartbeat" that beats at the exact same rhythm without speeding up or slowing down. In antique grandfather clocks, a swinging pendulum provides the steady tick. In modern digital wristwatches, a tiny quartz crystal vibrates exactly 32,768 times every single second when electric battery power touches it!',
      emoji: '⏱️'
    },
    howItWorks: {
      title: 'Inside a Clock Mechanism',
      points: [
        'The Oscillator (Heartbeat): A pendulum swinging or a quartz crystal vibrating at an unvarying frequency.',
        'The Escapement & Gears: Teeth gears that step forward one tooth with every single tick, turning the second, minute, and hour hands.',
        'The Power Source: A wound-up steel spring or a small chemical coin battery.'
      ]
    },
    funFacts: [
      'The most accurate clocks in the world are atomic clocks that count the vibrations of cesium atoms — they won’t lose 1 second in 300 million years!',
      'Before clocks existed, people told time with sundials using shadows cast by the sun, water clocks, and hourglass sand timers.',
      'There are 86,400 seconds in a single 24-hour day.'
    ],
    kidWords: [
      { word: 'Pendulum', emoji: '⚖️', meaning: 'A hanging weight that swings back and forth at a regular tempo.' },
      { word: 'Gear', emoji: '⚙️', meaning: 'A toothed wheel that interlocks with others to transmit rotational motion.' },
      { word: 'Quartz', emoji: '💎', meaning: 'A common crystal mineral that vibrates with electrical precision.' }
    ],
    didYouKnowOrigin: 'Why does a clock run "clockwise"? Because before mechanical clocks, northern hemisphere sundials had shadows moving from left to right across the top of the dial as the sun moved across the sky!',
    microQuiz: {
      question: 'How many seconds are in one complete minute?',
      options: ['60 seconds', '100 seconds', '10 seconds'],
      correctIndex: 0,
      explanation: 'There are exactly 60 seconds in 1 minute, and 60 minutes in 1 hour!'
    },
    seeAlso: [
      { id: 'wheels-gears', title: 'Wheels & Gears', category: 'how-things-work' },
      { id: 'the-sun', title: 'The Sun', category: 'solar-system' }
    ]
  },
  {
    id: 'wheels-gears',
    title: 'Wheels, Gears & Simple Machines',
    symbol: '⚙️',
    pronunciation: '(WEELZ and GEERZ)',
    category: 'how-things-work',
    tagline: 'The circular inventions that eliminated friction and gave humans mechanical superpowers.',
    analogy: {
      title: 'The Rolling Helpers That Make Heavy Things Light',
      story: 'Trying to drag a heavy boulder across the dirt is exhausting because friction pulls against you. But put that boulder on rolling logs (or a wheeled cart) and suddenly one person can push a 500-pound load with ease! Adding toothed gears lets a kid pedal a bicycle up a steep hill without straining.',
      emoji: '🚲'
    },
    howItWorks: {
      title: 'The 6 Classic Simple Machines',
      points: [
        'The Wheel & Axle: Turns sliding friction into smooth rolling motion.',
        'The Lever (Seesaw): Uses a fulcrum balance point to lift heavy weights with small effort.',
        'The Pulley: Uses ropes and grooved wheels to hoist objects straight up.',
        'The Inclined Plane (Ramp): Lets you push items up gradually instead of lifting straight up.'
      ]
    },
    funFacts: [
      'The wheel was invented over 5,500 years ago in ancient Mesopotamia (originally for spinning clay pottery, then for carts)!',
      'A multi-speed bicycle uses gears of different sizes so you can choose high speed or easy hill climbing.',
      'Can openers, Ferris wheels, escalators, and robot arms all rely on gears intermeshing together.'
    ],
    kidWords: [
      { word: 'Friction', emoji: '🔥', meaning: 'The resistance force created when two surfaces rub together.' },
      { word: 'Fulcrum', emoji: '📐', meaning: 'The pivot or support point on which a lever balances.' },
      { word: 'Axle', emoji: '🦯', meaning: 'The central rod on which a wheel rotates.' }
    ],
    didYouKnowOrigin: 'No animal in nature ever evolved a true spinning wheel and axle on its body, making the wheel one of humanity’s most unique inventions!',
    microQuiz: {
      question: 'What do gears with intermeshing teeth do?',
      options: ['Transfer rotational force and change speed or direction', 'Make wheels square', 'Stop all movement permanently'],
      correctIndex: 0,
      explanation: 'Gears lock their teeth together to multiply force, increase speed, or turn movement around corners!'
    },
    seeAlso: [
      { id: 'how-clocks-work', title: 'How Clocks Tell Time', category: 'how-things-work' },
      { id: 'bridges-engineering', title: 'Bridges & Engineering', category: 'how-things-work' }
    ]
  },
  {
    id: 'electricity-power',
    title: 'Electricity & Circuits',
    symbol: '⚡',
    pronunciation: '(ee-lek-TRIS-ih-tee and SER-kuts)',
    category: 'how-things-work',
    tagline: 'The flowing dance of tiny electrons that lights homes, runs TVs, and powers cities.',
    analogy: {
      title: 'The Water Pipe Loop of Invisible Electrons',
      story: 'Think of electricity like water flowing through a garden hose! The battery is like a water pump pushing electrons forward, the copper wires are like the water pipes, and a lightbulb is like a waterwheel that spins and glows bright as the flowing electrons pass through it!',
      emoji: '💡'
    },
    howItWorks: {
      title: 'The Magic of a Complete Circuit',
      points: [
        'Closed Loop: Electricity can ONLY flow if there is an unbroken circle from the power source back to it.',
        'The Switch: Flipping a light switch simply opens or closes the bridge in the wire loop!',
        'Conductors vs. Insulators: Metals like copper let electricity glide easily (conductors), while rubber and plastic block it safely (insulators).'
      ]
    },
    funFacts: [
      'Electricity travels through copper wires at nearly the speed of light — about 186,000 miles per second!',
      'A single lightning bolt contains enough electrical energy to toast 100,000 slices of bread!',
      'Your own body uses tiny electrical pulses to send signals through your nerves to wiggle your toes and beat your heart.'
    ],
    kidWords: [
      { word: 'Electron', emoji: '⚛️', meaning: 'A tiny negatively charged particle orbiting inside atoms.' },
      { word: 'Circuit', emoji: '🔄', meaning: 'A complete circular loop through which electric current can flow.' },
      { word: 'Conductor', emoji: '🔌', meaning: 'A material (like copper or silver) that allows electricity to flow freely.' }
    ],
    didYouKnowOrigin: 'The word "Electricity" comes from the ancient Greek word "elektron", which meant amber! The Greeks noticed that rubbing amber with wool created static electricity that picked up small feathers.',
    microQuiz: {
      question: 'What happens when you flip a light switch to "OFF"?',
      options: ['It opens a gap in the circuit so electricity stops flowing', 'It empties all electrons out onto the floor', 'It blows out a candle inside'],
      correctIndex: 0,
      explanation: 'Turning a switch off creates an open gap in the circuit loop, stopping electron flow safely!'
    },
    handsOnExperiment: {
      title: 'Static Electricity Balloon Bending Water',
      materials: ['A blown-up latex balloon', 'A piece of wool cloth (or your own clean, dry hair)', 'A gentle trickle of water from a sink faucet'],
      steps: [
        'Rub the balloon vigorously against your hair or wool for 20 seconds to load it with static electrons.',
        'Turn on the sink faucet so a super-thin, smooth stream of water is trickling down.',
        'Bring the rubbed side of the balloon close to the water stream without touching it.',
        'Watch the water stream visibly bend towards the balloon like magic!'
      ],
      explanation: 'The extra negative electrons on the balloon attract the positive side of water molecules, pulling the stream sideways!',
      emoji: '🎈'
    },
    kidTongueTwisterOrRhyme: 'Electric sparks energetically empower every exciting electronic engine!',
    seeAlso: [
      { id: 'lightning-thunder', title: 'Lightning & Thunder', category: 'earth-elements' },
      { id: 'how-internet-works', title: 'How the Internet Works', category: 'how-things-work' }
    ]
  },
  {
    id: 'how-cameras-work',
    title: 'How Cameras Work',
    symbol: '📷',
    pronunciation: '(KAM-er-uhz)',
    category: 'how-things-work',
    tagline: 'How glass lenses and digital sensors capture a fleeting slice of time into a photo.',
    analogy: {
      title: 'Painting with Real Sunlight onto a Grid of Buckets',
      story: 'A camera works just like the human eye! Sunlight bounces off your friend’s smile, enters through a curved glass lens that focuses the rays, and strikes a digital sensor chip covered in millions of tiny light-catcher buckets (pixels). Each pixel measures how much red, green, and blue light landed in its bucket!',
      emoji: '🖼️'
    },
    howItWorks: {
      title: 'Key Steps of Taking a Photo',
      points: [
        'The Aperture (Pupil): The adjustable opening that controls how much light enters the camera.',
        'The Shutter (Eyelid): A super-fast door that opens for 1/1000th of a second to freeze action without blur.',
        'The Sensor (Retina): A silicon chip made of millions of color-sensitive pixels that converts light into numbers.'
      ]
    },
    funFacts: [
      'The first photograph ever taken in 1826 required an 8-hour exposure in bright sunlight to show a courtyard view!',
      'Your phone’s camera sensor can record over 48 million pixels in a single snap.',
      'The word "Photography" literally means "Drawing with Light" in Greek ("photo" = light, "graph" = drawing).'
    ],
    kidWords: [
      { word: 'Pixel', emoji: '🟩', meaning: 'The tiny color dots that combine on a screen to form a full photo.' },
      { word: 'Aperture', emoji: '⭕', meaning: 'The circular opening in a lens that adjusts how much light enters.' },
      { word: 'Shutter', emoji: '🚪', meaning: 'The rapid mechanical door that opens and closes to expose light to the sensor.' }
    ],
    didYouKnowOrigin: 'Before digital chips, cameras used plastic film coated with light-sensitive silver salt crystals that had to be bathed in darkroom chemicals to reveal pictures!',
    microQuiz: {
      question: 'What does the Greek word "Photography" literally translate to?',
      options: ['Drawing with Light', 'Magic Mirror', 'Talking to Robots'],
      correctIndex: 0,
      explanation: '"Photo" means light and "graphy" means drawing or writing — literally drawing pictures with light rays!'
    },
    seeAlso: [
      { id: 'five-senses', title: 'The 5 Senses (Sight)', category: 'human-body' },
      { id: 'how-internet-works', title: 'How the Internet Works', category: 'how-things-work' }
    ]
  },
  {
    id: 'bridges-engineering',
    title: 'How Giant Bridges Stay Up',
    symbol: '🌉',
    pronunciation: '(BRIJ-ez and en-juh-NEER-ing)',
    category: 'how-things-work',
    tagline: 'The physics of suspension cables, concrete arches, and triangular trusses spanning wide rivers.',
    analogy: {
      title: 'The Tug-of-War Balance Across the Water',
      story: 'When thousands of heavy cars drive across a long suspension bridge (like the Golden Gate Bridge), how does it not collapse? Giant steel cables as thick as telephone poles pull upward with immense tension, anchoring into massive bedrock concrete blocks on the shores that hold everything steady in a giant, beautiful tug-of-war!',
      emoji: '🏗️'
    },
    howItWorks: {
      title: 'The 3 Main Bridge Designs',
      points: [
        'Beam & Truss Bridges: Use rigid interlocking triangles (trusses) because triangles cannot deform or fold under pressure!',
        'Arch Bridges: Squeeze weight down into the ground curves (compression), used by Romans 2,000 years ago.',
        'Suspension Bridges: Hang the roadway from curving vertical steel wire ropes anchored to tall tower piers.'
      ]
    },
    funFacts: [
      'The longest sea-crossing bridge in the world is the Hong Kong–Zhuhai–Macau Bridge — 34 miles long with an undersea tunnel!',
      'Triangles are the strongest geometric shape in engineering because all three sides support every push together.',
      'Roman aqueduct arch bridges built without any cement or glue are still standing and carrying water today after 2,000 years.'
    ],
    kidWords: [
      { word: 'Tension', emoji: '🪢', meaning: 'A pulling or stretching force in a rope or cable.' },
      { word: 'Compression', emoji: '🗜️', meaning: 'A squeezing or pushing-together force.' },
      { word: 'Truss', emoji: '📐', meaning: 'A rigid framework made of connected structural triangles.' }
    ],
    didYouKnowOrigin: 'The steel wire cables holding up the Brooklyn Bridge in New York were spun on site wire-by-wire in 1883 and stretch over 14,000 miles if laid out end-to-end!',
    microQuiz: {
      question: 'Which geometric shape is the strongest and most rigid for building bridges and towers?',
      options: ['Triangle', 'Square', 'Circle'],
      correctIndex: 0,
      explanation: 'Triangles are structurally rigid: you cannot bend a corner without changing the length of a side!'
    },
    handsOnExperiment: {
      title: 'The Paper Bridge Strength Test',
      materials: ['2 stacked books of equal height', 'A sheet of paper', 'Pennies or small coins'],
      steps: [
        'Place the two books 4 inches apart.',
        'Lay a flat sheet of paper across the gap as a bridge. Place pennies on it — it collapses with just 2 or 3 pennies!',
        'Now accordion-fold another sheet of paper into tight zig-zag triangular ridges (corrugated shape) and lay it across the gap.',
        'Stack pennies on it: The folded paper bridge can now hold 30+ pennies without falling!'
      ],
      explanation: 'The folds create a series of rigid triangles that distribute weight sideways across the book supports!',
      emoji: '🪙'
    },
    seeAlso: [
      { id: 'geometric-shapes', title: 'Shapes & Geometry', category: 'numbers' },
      { id: 'wheels-gears', title: 'Wheels & Gears', category: 'how-things-work' }
    ]
  },
  {
    id: 'submarines-diving',
    title: 'How Submarines Dive & Float',
    symbol: '🤿',
    pronunciation: '(SUB-muh-reenz and DYE-ving)',
    category: 'how-things-work',
    tagline: 'Controlling buoyancy with giant water ballast tanks to explore the deep ocean abyss.',
    analogy: {
      title: 'The Swimming Balloon with Built-in Water Tanks',
      story: 'A submarine can choose when to float like a cork or sink like a stone! It has giant hollow ballast tanks between its hulls. When it wants to dive, valves open to let heavy ocean water rush in, pulling the submarine deep down. To rise back to the sunlight, blasts of high-pressure air shoot the water out!',
      emoji: '⚓'
    },
    howItWorks: {
      title: 'The Physics of Buoyancy',
      points: [
        'Surface Mode: Ballast tanks are filled with light air — the submarine floats high on ocean waves.',
        'Diving Mode: Flood gates open at the bottom, vents open at the top, and heavy sea water fills the tanks.',
        'Surfacing: Compressed air tanks blast pressurized air into the ballast tanks, blowing water back out through the bottom.'
      ]
    },
    funFacts: [
      'Some scientific research submarines can dive nearly 36,000 feet down to the bottom of the Mariana Trench!',
      'Nuclear submarines make their own fresh drinking water and oxygen from seawater, staying submerged for months without surfacing.',
      'Submarines use Sonar (sound echoes) to navigate in pitch-black deep waters without hitting underwater mountains.'
    ],
    kidWords: [
      { word: 'Buoyancy', emoji: '🛟', meaning: 'The upward force that makes objects float in water or air.' },
      { word: 'Ballast', emoji: '🪨', meaning: 'Heavy material or water placed in tanks to control balance and depth.' },
      { word: 'Sonar', emoji: '🔊', meaning: 'Using sound wave echoes to detect underwater objects.' }
    ],
    didYouKnowOrigin: 'The first working military submarine, called "The Turtle", was invented in 1775 and was made of hand-carved oak wood shaped like a giant egg and powered by foot pedals!',
    microQuiz: {
      question: 'What do submarines fill their ballast tanks with when they want to surface back up to the air?',
      options: ['High-pressure compressed air', 'Heavy rocks', 'More sea water'],
      correctIndex: 0,
      explanation: 'Blowing compressed air into the tanks pushes out heavy water, making the submarine buoyant enough to float up!'
    },
    seeAlso: [
      { id: 'world-oceans', title: 'World Oceans', category: 'countries-world' },
      { id: 'water-element', title: 'Water (H2O)', category: 'earth-elements' }
    ]
  }
];
